dist: xenial
language: python
python: "3.7"

jobs:
    include:
      - stage: lint
        script: poetry run invoke lint
      - stage: test
        before_script:
          # Install pyenv
          - export PATH="$PYENV_ROOT/bin:$PATH"
          - curl https://pyenv.run | bash
          - eval "$(pyenv init -)"
          # Install Python versions
          - pyenv install 3.4.9
          - pyenv install 3.5.7
          - pyenv install 3.6.8
          - pyenv install 3.7.3
          - pyenv install 3.8-dev
          - pyenv local 3.4.9 3.5.7 3.6.8 3.7.3 3.8-dev
        script: poetry run invoke test --all
        after_success: poetry run coverage report

before_install: pip install poetry
install: poetry install
