dist: xenial
language: minimal

cache:
    directories:
      - $HOME/.cache/pip
      - $HOME/.cache/pypoetry
      - $HOME/.ccache
      - .tox

jobs:
    include:
      - stage: lint
        script: poetry run invoke lint
      - stage: test
        before_script:
          - pyenv install -s 3.5.9
          - pyenv install -s 3.6.9
          - pyenv install -s 3.7.6
          - pyenv local 3.8.1 3.7.6 3.5.9 3.6.9
        script: poetry run invoke test --all --cov --no-cov-report
        after_success:
          - poetry run coverage report
          - poetry run coverage xml && bash <(curl -s https://codecov.io/bash)

before_install:
  - git clone https://github.com/pyenv/pyenv.git ~/.pyenv
  - git clone https://github.com/pyenv/pyenv-ccache.git ~/.pyenv/plugins/pyenv-ccache
  - export PYENV_ROOT="$HOME/.pyenv"
  - export PATH="$PYENV_ROOT/bin:$PATH"
  - eval "$(pyenv init -)"
  - pyenv --version
install:
  - pyenv install -s 3.8.1
  - pyenv local 3.8.1
  - python --version
  - pip --version
  - pip install --user poetry
  - poetry --version
  - poetry install
