[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "django-class-settings"
version = "0.3.1-dev"
description = "Effortless class-based settings for Django."
license = "ISC"
authors = ["orlnub123 <orlnub123@gmail.com>"]
readme = "README.md"
repository = "https://github.com/orlnub123/django-class-settings"
documentation = "https://django-class-settings.readthedocs.io/"
keywords = ["django", "settings", "configuration"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Web Environment",
    "Framework :: Django",
    "Framework :: Django :: 1.11",
    "Framework :: Django :: 2.0",
    "Framework :: Django :: 2.1",
    "Framework :: Django :: 2.2",
    "Framework :: Django :: 3.0",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Utilities"
]
packages = [{include = "class_settings", from = "src"}]

[tool.poetry.dependencies]
python = "^3.5"
django = "*"
python-dotenv = ">=0.7"

[tool.poetry.dev-dependencies]
black = {version = "^19.10b", python = "^3.6"}
coverage = {version = "^5.0", extras = ["toml"]}
flake8 = "^3.7"
flake8-bugbear = "^19.8"
invoke = "^1.3"
isort = {version = "^4.3.5", extras = ["pyproject"]}
pre-commit = "^1.20"
pytest = "^5.3"
tox = "^3.14"

[tool.coverage.run]
branch = true
source = ["class_settings"]

[tool.coverage.paths]
source = ["src/", ".tox/*/site-packages/"]

[tool.coverage.report]
show_missing = true

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 88
