site_name: django-class-settings
repo_url: https://github.com/orlnub123/django-class-settings
site_description: Effortless class-based settings for Django.
copyright: Copyright © 2018-2019 orlnub123.
theme: readthedocs
docs_dir: files

nav:
    - Index: index.md
    - Tutorial: tutorial.md
    - Changelog: changelog.md

plugins:
    - changelog_generator
    - index_generator
